spring:
  application:
    name: hinkali-cloud
  data:
    rest:
      base-path: /data-api
    mongodb:
      host: localhost
      port: 27017
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis