spring:
  application:
    name: hinkali-cloud
  data:
    rest:
      base-path: /data-api
    mongodb:
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: rmhinkali
    password: rmhinalipassword
    template:
      exchange: hinkalicloud.order
      routing-key: kitchens.central